// +build go1.6

// Code generated by codecgen - DO NOT EDIT.

package model

import (
	"errors"
	codec1978 "github.com/ugorji/go/codec"
	pkg1_wrp "github.com/xmidt-org/wrp-go/wrp"
	"runtime"
	"strconv"
)

const (
	// ----- content types ----
	codecSelferCcUTF86972 = 1
	codecSelferCcRAW6972  = 255
	// ----- value types used ----
	codecSelferValueTypeArray6972     = 10
	codecSelferValueTypeMap6972       = 9
	codecSelferValueTypeString6972    = 6
	codecSelferValueTypeInt6972       = 2
	codecSelferValueTypeUint6972      = 3
	codecSelferValueTypeFloat6972     = 4
	codecSelferValueTypeNil6972       = 1
	codecSelferBitsize6972            = uint8(32 << (^uint(0) >> 63))
	codecSelferDecContainerLenNil6972 = -2147483648
)

var (
	errCodecSelferOnlyMapOrArrayEncodeToStruct6972 = errors.New(`only encoded map or array can be decoded into a struct`)
)

type codecSelfer6972 struct{}

func codecSelfer6972False() bool { return false }

func init() {
	if codec1978.GenVersion != 16 {
		_, file, _, _ := runtime.Caller(0)
		ver := strconv.FormatInt(int64(codec1978.GenVersion), 10)
		panic("codecgen version mismatch: current: 16, need " + ver + ". Re-generate file: " + file)
	}
	if false { // reference the types, but skip this branch at build/run time
		var _ pkg1_wrp.Message
	}
}

func (x *Event) CodecEncodeSelf(e *codec1978.Encoder) {
	var h codecSelfer6972
	z, r := codec1978.GenHelperEncoder(e)
	_, _, _ = h, z, r
	if x == nil {
		r.EncodeNil()
	} else {
		yysep2 := !z.EncBinary()
		yy2arr2 := z.EncBasicHandle().StructToArray
		_, _ = yysep2, yy2arr2
		const yyr2 bool = false // struct tag has 'toArray'
		var yyq2 = [18]bool{    // should field at this index be written?
			true,                             // Type
			x.Source != "",                   // Source
			x.Destination != "",              // Destination
			x.TransactionUUID != "",          // TransactionUUID
			x.ContentType != "",              // ContentType
			x.Accept != "",                   // Accept
			x.Status != nil,                  // Status
			x.RequestDeliveryResponse != nil, // RequestDeliveryResponse
			len(x.Headers) != 0,              // Headers
			len(x.Metadata) != 0,             // Metadata
			len(x.Spans) != 0,                // Spans
			x.IncludeSpans != nil,            // IncludeSpans
			x.Path != "",                     // Path
			len(x.Payload) != 0,              // Payload
			x.ServiceName != "",              // ServiceName
			x.URL != "",                      // URL
			len(x.PartnerIDs) != 0,           // PartnerIDs
			x.BirthDate != 0,                 // BirthDate
		}
		_ = yyq2
		var yyn9 bool = x.Message.Status == nil
		var yyn10 bool = x.Message.RequestDeliveryResponse == nil
		var yyn14 bool = x.Message.IncludeSpans == nil
		if yyr2 || yy2arr2 {
			z.EncWriteArrayStart(18)
			z.EncWriteArrayElem()
			if yyxt21 := z.Extension(z.I2Rtid(x.Message.Type)); yyxt21 != nil {
				z.EncExtension(x.Message.Type, yyxt21)
			} else {
				r.EncodeInt(int64(x.Message.Type))
			}
			z.EncWriteArrayElem()
			if yyq2[1] {
				r.EncodeString(string(x.Message.Source))
			} else {
				r.EncodeString("")
			}
			z.EncWriteArrayElem()
			if yyq2[2] {
				r.EncodeString(string(x.Message.Destination))
			} else {
				r.EncodeString("")
			}
			z.EncWriteArrayElem()
			if yyq2[3] {
				r.EncodeString(string(x.Message.TransactionUUID))
			} else {
				r.EncodeString("")
			}
			z.EncWriteArrayElem()
			if yyq2[4] {
				r.EncodeString(string(x.Message.ContentType))
			} else {
				r.EncodeString("")
			}
			z.EncWriteArrayElem()
			if yyq2[5] {
				r.EncodeString(string(x.Message.Accept))
			} else {
				r.EncodeString("")
			}
			if yyn9 {
				z.EncWriteArrayElem()
				r.EncodeNil()
			} else {
				z.EncWriteArrayElem()
				if yyq2[6] {
					yy27 := *x.Message.Status
					r.EncodeInt(int64(yy27))
				} else {
					r.EncodeNil()
				}
			}
			if yyn10 {
				z.EncWriteArrayElem()
				r.EncodeNil()
			} else {
				z.EncWriteArrayElem()
				if yyq2[7] {
					yy29 := *x.Message.RequestDeliveryResponse
					r.EncodeInt(int64(yy29))
				} else {
					r.EncodeNil()
				}
			}
			z.EncWriteArrayElem()
			if yyq2[8] {
				if x.Message.Headers == nil {
					r.EncodeNil()
				} else {
					z.F.EncSliceStringV(x.Message.Headers, e)
				} // end block: if x.Message.Headers slice == nil
			} else {
				r.EncodeNil()
			}
			z.EncWriteArrayElem()
			if yyq2[9] {
				if x.Message.Metadata == nil {
					r.EncodeNil()
				} else {
					z.F.EncMapStringStringV(x.Message.Metadata, e)
				} // end block: if x.Message.Metadata map == nil
			} else {
				r.EncodeNil()
			}
			z.EncWriteArrayElem()
			if yyq2[10] {
				if x.Message.Spans == nil {
					r.EncodeNil()
				} else {
					h.encSliceSlicestring(([][]string)(x.Message.Spans), e)
				} // end block: if x.Message.Spans slice == nil
			} else {
				r.EncodeNil()
			}
			if yyn14 {
				z.EncWriteArrayElem()
				r.EncodeNil()
			} else {
				z.EncWriteArrayElem()
				if yyq2[11] {
					yy34 := *x.Message.IncludeSpans
					r.EncodeBool(bool(yy34))
				} else {
					r.EncodeNil()
				}
			}
			z.EncWriteArrayElem()
			if yyq2[12] {
				r.EncodeString(string(x.Message.Path))
			} else {
				r.EncodeString("")
			}
			z.EncWriteArrayElem()
			if yyq2[13] {
				if x.Message.Payload == nil {
					r.EncodeNil()
				} else {
					r.EncodeStringBytesRaw([]byte(x.Message.Payload))
				} // end block: if x.Message.Payload slice == nil
			} else {
				r.EncodeNil()
			}
			z.EncWriteArrayElem()
			if yyq2[14] {
				r.EncodeString(string(x.Message.ServiceName))
			} else {
				r.EncodeString("")
			}
			z.EncWriteArrayElem()
			if yyq2[15] {
				r.EncodeString(string(x.Message.URL))
			} else {
				r.EncodeString("")
			}
			z.EncWriteArrayElem()
			if yyq2[16] {
				if x.Message.PartnerIDs == nil {
					r.EncodeNil()
				} else {
					z.F.EncSliceStringV(x.Message.PartnerIDs, e)
				} // end block: if x.Message.PartnerIDs slice == nil
			} else {
				r.EncodeNil()
			}
			z.EncWriteArrayElem()
			if yyq2[17] {
				r.EncodeInt(int64(x.BirthDate))
			} else {
				r.EncodeInt(0)
			}
			z.EncWriteArrayEnd()
		} else {
			var yynn2 int
			for _, b := range yyq2 {
				if b {
					yynn2++
				}
			}
			z.EncWriteMapStart(yynn2)
			yynn2 = 0
			z.EncWriteMapElemKey()
			r.EncodeString(`msg_type`)
			z.EncWriteMapElemValue()
			if yyxt42 := z.Extension(z.I2Rtid(x.Message.Type)); yyxt42 != nil {
				z.EncExtension(x.Message.Type, yyxt42)
			} else {
				r.EncodeInt(int64(x.Message.Type))
			}
			if yyq2[1] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"source\"")
				} else {
					r.EncodeString(`source`)
				}
				z.EncWriteMapElemValue()
				r.EncodeString(string(x.Message.Source))
			}
			if yyq2[2] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"dest\"")
				} else {
					r.EncodeString(`dest`)
				}
				z.EncWriteMapElemValue()
				r.EncodeString(string(x.Message.Destination))
			}
			if yyq2[3] {
				z.EncWriteMapElemKey()
				r.EncodeString(`transaction_uuid`)
				z.EncWriteMapElemValue()
				r.EncodeString(string(x.Message.TransactionUUID))
			}
			if yyq2[4] {
				z.EncWriteMapElemKey()
				r.EncodeString(`content_type`)
				z.EncWriteMapElemValue()
				r.EncodeString(string(x.Message.ContentType))
			}
			if yyq2[5] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"accept\"")
				} else {
					r.EncodeString(`accept`)
				}
				z.EncWriteMapElemValue()
				r.EncodeString(string(x.Message.Accept))
			}
			if yyq2[6] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"status\"")
				} else {
					r.EncodeString(`status`)
				}
				z.EncWriteMapElemValue()
				if yyn9 {
					r.EncodeNil()
				} else {
					yy48 := *x.Message.Status
					r.EncodeInt(int64(yy48))
				}
			}
			if yyq2[7] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"rdr\"")
				} else {
					r.EncodeString(`rdr`)
				}
				z.EncWriteMapElemValue()
				if yyn10 {
					r.EncodeNil()
				} else {
					yy50 := *x.Message.RequestDeliveryResponse
					r.EncodeInt(int64(yy50))
				}
			}
			if yyq2[8] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"headers\"")
				} else {
					r.EncodeString(`headers`)
				}
				z.EncWriteMapElemValue()
				if x.Message.Headers == nil {
					r.EncodeNil()
				} else {
					z.F.EncSliceStringV(x.Message.Headers, e)
				} // end block: if x.Message.Headers slice == nil
			}
			if yyq2[9] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"metadata\"")
				} else {
					r.EncodeString(`metadata`)
				}
				z.EncWriteMapElemValue()
				if x.Message.Metadata == nil {
					r.EncodeNil()
				} else {
					z.F.EncMapStringStringV(x.Message.Metadata, e)
				} // end block: if x.Message.Metadata map == nil
			}
			if yyq2[10] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"spans\"")
				} else {
					r.EncodeString(`spans`)
				}
				z.EncWriteMapElemValue()
				if x.Message.Spans == nil {
					r.EncodeNil()
				} else {
					h.encSliceSlicestring(([][]string)(x.Message.Spans), e)
				} // end block: if x.Message.Spans slice == nil
			}
			if yyq2[11] {
				z.EncWriteMapElemKey()
				r.EncodeString(`include_spans`)
				z.EncWriteMapElemValue()
				if yyn14 {
					r.EncodeNil()
				} else {
					yy55 := *x.Message.IncludeSpans
					r.EncodeBool(bool(yy55))
				}
			}
			if yyq2[12] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"path\"")
				} else {
					r.EncodeString(`path`)
				}
				z.EncWriteMapElemValue()
				r.EncodeString(string(x.Message.Path))
			}
			if yyq2[13] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"payload\"")
				} else {
					r.EncodeString(`payload`)
				}
				z.EncWriteMapElemValue()
				if x.Message.Payload == nil {
					r.EncodeNil()
				} else {
					r.EncodeStringBytesRaw([]byte(x.Message.Payload))
				} // end block: if x.Message.Payload slice == nil
			}
			if yyq2[14] {
				z.EncWriteMapElemKey()
				r.EncodeString(`service_name`)
				z.EncWriteMapElemValue()
				r.EncodeString(string(x.Message.ServiceName))
			}
			if yyq2[15] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"url\"")
				} else {
					r.EncodeString(`url`)
				}
				z.EncWriteMapElemValue()
				r.EncodeString(string(x.Message.URL))
			}
			if yyq2[16] {
				z.EncWriteMapElemKey()
				r.EncodeString(`partner_ids`)
				z.EncWriteMapElemValue()
				if x.Message.PartnerIDs == nil {
					r.EncodeNil()
				} else {
					z.F.EncSliceStringV(x.Message.PartnerIDs, e)
				} // end block: if x.Message.PartnerIDs slice == nil
			}
			if yyq2[17] {
				z.EncWriteMapElemKey()
				r.EncodeString(`birth_date`)
				z.EncWriteMapElemValue()
				r.EncodeInt(int64(x.BirthDate))
			}
			z.EncWriteMapEnd()
		}
	}
}

func (x *Event) CodecDecodeSelf(d *codec1978.Decoder) {
	var h codecSelfer6972
	z, r := codec1978.GenHelperDecoder(d)
	_, _, _ = h, z, r
	yyct2 := r.ContainerType()
	if yyct2 == codecSelferValueTypeNil6972 {
		*(x) = Event{}
	} else if yyct2 == codecSelferValueTypeMap6972 {
		yyl2 := z.DecReadMapStart()
		if yyl2 == 0 {
		} else {
			x.codecDecodeSelfFromMap(yyl2, d)
		}
		z.DecReadMapEnd()
	} else if yyct2 == codecSelferValueTypeArray6972 {
		yyl2 := z.DecReadArrayStart()
		if yyl2 != 0 {
			x.codecDecodeSelfFromArray(yyl2, d)
		}
		z.DecReadArrayEnd()
	} else {
		panic(errCodecSelferOnlyMapOrArrayEncodeToStruct6972)
	}
}

func (x *Event) codecDecodeSelfFromMap(l int, d *codec1978.Decoder) {
	var h codecSelfer6972
	z, r := codec1978.GenHelperDecoder(d)
	_, _, _ = h, z, r
	var yyhl3 bool = l >= 0
	for yyj3 := 0; ; yyj3++ {
		if yyhl3 {
			if yyj3 >= l {
				break
			}
		} else {
			if z.DecCheckBreak() {
				break
			}
		}
		z.DecReadMapElemKey()
		yys3 := z.StringView(r.DecodeStringAsBytes())
		z.DecReadMapElemValue()
		switch yys3 {
		case "msg_type":
			if yyxt5 := z.Extension(z.I2Rtid(x.Message.Type)); yyxt5 != nil {
				z.DecExtension(x.Message.Type, yyxt5)
			} else {
				x.Message.Type = (pkg1_wrp.MessageType)(r.DecodeInt64())
			}
		case "source":
			x.Message.Source = (string)(string(r.DecodeStringAsBytes()))
		case "dest":
			x.Message.Destination = (string)(string(r.DecodeStringAsBytes()))
		case "transaction_uuid":
			x.Message.TransactionUUID = (string)(string(r.DecodeStringAsBytes()))
		case "content_type":
			x.Message.ContentType = (string)(string(r.DecodeStringAsBytes()))
		case "accept":
			x.Message.Accept = (string)(string(r.DecodeStringAsBytes()))
		case "status":
			if r.TryNil() {
				if x.Message.Status != nil { // remove the if-true
					x.Message.Status = nil
				}
			} else {
				if x.Message.Status == nil {
					x.Message.Status = new(int64)
				}
				*x.Message.Status = (int64)(r.DecodeInt64())
			}
		case "rdr":
			if r.TryNil() {
				if x.Message.RequestDeliveryResponse != nil { // remove the if-true
					x.Message.RequestDeliveryResponse = nil
				}
			} else {
				if x.Message.RequestDeliveryResponse == nil {
					x.Message.RequestDeliveryResponse = new(int64)
				}
				*x.Message.RequestDeliveryResponse = (int64)(r.DecodeInt64())
			}
		case "headers":
			z.F.DecSliceStringX(&x.Message.Headers, d)
		case "metadata":
			z.F.DecMapStringStringX(&x.Message.Metadata, d)
		case "spans":
			h.decSliceSlicestring((*[][]string)(&x.Message.Spans), d)
		case "include_spans":
			if r.TryNil() {
				if x.Message.IncludeSpans != nil { // remove the if-true
					x.Message.IncludeSpans = nil
				}
			} else {
				if x.Message.IncludeSpans == nil {
					x.Message.IncludeSpans = new(bool)
				}
				*x.Message.IncludeSpans = (bool)(r.DecodeBool())
			}
		case "path":
			x.Message.Path = (string)(string(r.DecodeStringAsBytes()))
		case "payload":
			x.Message.Payload = r.DecodeBytes(([]byte)(x.Message.Payload), false)
		case "service_name":
			x.Message.ServiceName = (string)(string(r.DecodeStringAsBytes()))
		case "url":
			x.Message.URL = (string)(string(r.DecodeStringAsBytes()))
		case "partner_ids":
			z.F.DecSliceStringX(&x.Message.PartnerIDs, d)
		case "birth_date":
			x.BirthDate = (int64)(r.DecodeInt64())
		default:
			z.DecStructFieldNotFound(-1, yys3)
		} // end switch yys3
	} // end for yyj3
}

func (x *Event) codecDecodeSelfFromArray(l int, d *codec1978.Decoder) {
	var h codecSelfer6972
	z, r := codec1978.GenHelperDecoder(d)
	_, _, _ = h, z, r
	var yyj31 int
	var yyb31 bool
	var yyhl31 bool = l >= 0
	yyj31++
	if yyhl31 {
		yyb31 = yyj31 > l
	} else {
		yyb31 = z.DecCheckBreak()
	}
	if yyb31 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	if yyxt33 := z.Extension(z.I2Rtid(x.Message.Type)); yyxt33 != nil {
		z.DecExtension(x.Message.Type, yyxt33)
	} else {
		x.Message.Type = (pkg1_wrp.MessageType)(r.DecodeInt64())
	}
	yyj31++
	if yyhl31 {
		yyb31 = yyj31 > l
	} else {
		yyb31 = z.DecCheckBreak()
	}
	if yyb31 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	x.Message.Source = (string)(string(r.DecodeStringAsBytes()))
	yyj31++
	if yyhl31 {
		yyb31 = yyj31 > l
	} else {
		yyb31 = z.DecCheckBreak()
	}
	if yyb31 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	x.Message.Destination = (string)(string(r.DecodeStringAsBytes()))
	yyj31++
	if yyhl31 {
		yyb31 = yyj31 > l
	} else {
		yyb31 = z.DecCheckBreak()
	}
	if yyb31 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	x.Message.TransactionUUID = (string)(string(r.DecodeStringAsBytes()))
	yyj31++
	if yyhl31 {
		yyb31 = yyj31 > l
	} else {
		yyb31 = z.DecCheckBreak()
	}
	if yyb31 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	x.Message.ContentType = (string)(string(r.DecodeStringAsBytes()))
	yyj31++
	if yyhl31 {
		yyb31 = yyj31 > l
	} else {
		yyb31 = z.DecCheckBreak()
	}
	if yyb31 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	x.Message.Accept = (string)(string(r.DecodeStringAsBytes()))
	yyj31++
	if yyhl31 {
		yyb31 = yyj31 > l
	} else {
		yyb31 = z.DecCheckBreak()
	}
	if yyb31 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	if r.TryNil() {
		if x.Message.Status != nil { // remove the if-true
			x.Message.Status = nil
		}
	} else {
		if x.Message.Status == nil {
			x.Message.Status = new(int64)
		}
		*x.Message.Status = (int64)(r.DecodeInt64())
	}
	yyj31++
	if yyhl31 {
		yyb31 = yyj31 > l
	} else {
		yyb31 = z.DecCheckBreak()
	}
	if yyb31 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	if r.TryNil() {
		if x.Message.RequestDeliveryResponse != nil { // remove the if-true
			x.Message.RequestDeliveryResponse = nil
		}
	} else {
		if x.Message.RequestDeliveryResponse == nil {
			x.Message.RequestDeliveryResponse = new(int64)
		}
		*x.Message.RequestDeliveryResponse = (int64)(r.DecodeInt64())
	}
	yyj31++
	if yyhl31 {
		yyb31 = yyj31 > l
	} else {
		yyb31 = z.DecCheckBreak()
	}
	if yyb31 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	z.F.DecSliceStringX(&x.Message.Headers, d)
	yyj31++
	if yyhl31 {
		yyb31 = yyj31 > l
	} else {
		yyb31 = z.DecCheckBreak()
	}
	if yyb31 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	z.F.DecMapStringStringX(&x.Message.Metadata, d)
	yyj31++
	if yyhl31 {
		yyb31 = yyj31 > l
	} else {
		yyb31 = z.DecCheckBreak()
	}
	if yyb31 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSliceSlicestring((*[][]string)(&x.Message.Spans), d)
	yyj31++
	if yyhl31 {
		yyb31 = yyj31 > l
	} else {
		yyb31 = z.DecCheckBreak()
	}
	if yyb31 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	if r.TryNil() {
		if x.Message.IncludeSpans != nil { // remove the if-true
			x.Message.IncludeSpans = nil
		}
	} else {
		if x.Message.IncludeSpans == nil {
			x.Message.IncludeSpans = new(bool)
		}
		*x.Message.IncludeSpans = (bool)(r.DecodeBool())
	}
	yyj31++
	if yyhl31 {
		yyb31 = yyj31 > l
	} else {
		yyb31 = z.DecCheckBreak()
	}
	if yyb31 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	x.Message.Path = (string)(string(r.DecodeStringAsBytes()))
	yyj31++
	if yyhl31 {
		yyb31 = yyj31 > l
	} else {
		yyb31 = z.DecCheckBreak()
	}
	if yyb31 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	x.Message.Payload = r.DecodeBytes(([]byte)(x.Message.Payload), false)
	yyj31++
	if yyhl31 {
		yyb31 = yyj31 > l
	} else {
		yyb31 = z.DecCheckBreak()
	}
	if yyb31 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	x.Message.ServiceName = (string)(string(r.DecodeStringAsBytes()))
	yyj31++
	if yyhl31 {
		yyb31 = yyj31 > l
	} else {
		yyb31 = z.DecCheckBreak()
	}
	if yyb31 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	x.Message.URL = (string)(string(r.DecodeStringAsBytes()))
	yyj31++
	if yyhl31 {
		yyb31 = yyj31 > l
	} else {
		yyb31 = z.DecCheckBreak()
	}
	if yyb31 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	z.F.DecSliceStringX(&x.Message.PartnerIDs, d)
	yyj31++
	if yyhl31 {
		yyb31 = yyj31 > l
	} else {
		yyb31 = z.DecCheckBreak()
	}
	if yyb31 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	x.BirthDate = (int64)(r.DecodeInt64())
	for {
		yyj31++
		if yyhl31 {
			yyb31 = yyj31 > l
		} else {
			yyb31 = z.DecCheckBreak()
		}
		if yyb31 {
			break
		}
		z.DecReadArrayElem()
		z.DecStructFieldNotFound(yyj31-1, "")
	}
}

func (x codecSelfer6972) encSliceSlicestring(v [][]string, e *codec1978.Encoder) {
	var h codecSelfer6972
	z, r := codec1978.GenHelperEncoder(e)
	_, _, _ = h, z, r
	if v == nil {
		r.EncodeNil()
		return
	}
	z.EncWriteArrayStart(len(v))
	for _, yyv1 := range v {
		z.EncWriteArrayElem()
		if yyv1 == nil {
			r.EncodeNil()
		} else {
			z.F.EncSliceStringV(yyv1, e)
		} // end block: if yyv1 slice == nil
	}
	z.EncWriteArrayEnd()
}

func (x codecSelfer6972) decSliceSlicestring(v *[][]string, d *codec1978.Decoder) {
	var h codecSelfer6972
	z, r := codec1978.GenHelperDecoder(d)
	_, _, _ = h, z, r

	yyv1 := *v
	yyh1, yyl1 := z.DecSliceHelperStart()
	var yyc1 bool
	_ = yyc1
	if yyh1.IsNil {
		if yyv1 != nil {
			yyv1 = nil
			yyc1 = true
		}
	} else if yyl1 == 0 {
		if yyv1 == nil {
			yyv1 = [][]string{}
			yyc1 = true
		} else if len(yyv1) != 0 {
			yyv1 = yyv1[:0]
			yyc1 = true
		}
	} else {
		yyhl1 := yyl1 > 0
		var yyrl1 int
		_ = yyrl1
		if yyhl1 {
			if yyl1 > cap(yyv1) {
				yyrl1 = z.DecInferLen(yyl1, z.DecBasicHandle().MaxInitLen, 24)
				if yyrl1 <= cap(yyv1) {
					yyv1 = yyv1[:yyrl1]
				} else {
					yyv1 = make([][]string, yyrl1)
				}
				yyc1 = true
			} else if yyl1 != len(yyv1) {
				yyv1 = yyv1[:yyl1]
				yyc1 = true
			}
		}
		var yyj1 int
		for yyj1 = 0; (yyhl1 && yyj1 < yyl1) || !(yyhl1 || z.DecCheckBreak()); yyj1++ { // bounds-check-elimination
			if yyj1 == 0 && yyv1 == nil {
				if yyhl1 {
					yyrl1 = z.DecInferLen(yyl1, z.DecBasicHandle().MaxInitLen, 24)
				} else {
					yyrl1 = 8
				}
				yyv1 = make([][]string, yyrl1)
				yyc1 = true
			}
			yyh1.ElemContainerState(yyj1)
			var yydb1 bool
			if yyj1 >= len(yyv1) {
				yyv1 = append(yyv1, nil)
				yyc1 = true
			}
			if yydb1 {
				z.DecSwallow()
			} else {
				z.F.DecSliceStringX(&yyv1[yyj1], d)
			}
		}
		if yyj1 < len(yyv1) {
			yyv1 = yyv1[:yyj1]
			yyc1 = true
		} else if yyj1 == 0 && yyv1 == nil {
			yyv1 = make([][]string, 0)
			yyc1 = true
		}
	}
	yyh1.End()
	if yyc1 {
		*v = yyv1
	}
}

func (x codecSelfer6972) encSlicestring(v []string, e *codec1978.Encoder) {
	var h codecSelfer6972
	z, r := codec1978.GenHelperEncoder(e)
	_, _, _ = h, z, r
	if v == nil {
		r.EncodeNil()
		return
	}
	z.EncWriteArrayStart(len(v))
	for _, yyv1 := range v {
		z.EncWriteArrayElem()
		r.EncodeString(string(yyv1))
	}
	z.EncWriteArrayEnd()
}

func (x codecSelfer6972) decSlicestring(v *[]string, d *codec1978.Decoder) {
	var h codecSelfer6972
	z, r := codec1978.GenHelperDecoder(d)
	_, _, _ = h, z, r

	yyv1 := *v
	yyh1, yyl1 := z.DecSliceHelperStart()
	var yyc1 bool
	_ = yyc1
	if yyh1.IsNil {
		if yyv1 != nil {
			yyv1 = nil
			yyc1 = true
		}
	} else if yyl1 == 0 {
		if yyv1 == nil {
			yyv1 = []string{}
			yyc1 = true
		} else if len(yyv1) != 0 {
			yyv1 = yyv1[:0]
			yyc1 = true
		}
	} else {
		yyhl1 := yyl1 > 0
		var yyrl1 int
		_ = yyrl1
		if yyhl1 {
			if yyl1 > cap(yyv1) {
				yyrl1 = z.DecInferLen(yyl1, z.DecBasicHandle().MaxInitLen, 16)
				if yyrl1 <= cap(yyv1) {
					yyv1 = yyv1[:yyrl1]
				} else {
					yyv1 = make([]string, yyrl1)
				}
				yyc1 = true
			} else if yyl1 != len(yyv1) {
				yyv1 = yyv1[:yyl1]
				yyc1 = true
			}
		}
		var yyj1 int
		for yyj1 = 0; (yyhl1 && yyj1 < yyl1) || !(yyhl1 || z.DecCheckBreak()); yyj1++ { // bounds-check-elimination
			if yyj1 == 0 && yyv1 == nil {
				if yyhl1 {
					yyrl1 = z.DecInferLen(yyl1, z.DecBasicHandle().MaxInitLen, 16)
				} else {
					yyrl1 = 8
				}
				yyv1 = make([]string, yyrl1)
				yyc1 = true
			}
			yyh1.ElemContainerState(yyj1)
			var yydb1 bool
			if yyj1 >= len(yyv1) {
				yyv1 = append(yyv1, "")
				yyc1 = true
			}
			if yydb1 {
				z.DecSwallow()
			} else {
				yyv1[yyj1] = (string)(string(r.DecodeStringAsBytes()))
			}
		}
		if yyj1 < len(yyv1) {
			yyv1 = yyv1[:yyj1]
			yyc1 = true
		} else if yyj1 == 0 && yyv1 == nil {
			yyv1 = make([]string, 0)
			yyc1 = true
		}
	}
	yyh1.End()
	if yyc1 {
		*v = yyv1
	}
}
