// SPDX-FileCopyrightText: 2025 Comcast Cable Communications Management, LLC
// SPDX-License-Identifier: Apache-2.0

//go:build go1.6
// +build go1.6

// Code generated by codecgen - DO NOT EDIT.

package model

import (
	"errors"
	codec1978 "github.com/ugorji/go/codec"
	pkg1_v3 "github.com/xmidt-org/wrp-go/v3"
	"runtime"
	"strconv"
)

const (
	// ----- content types ----
	codecSelferCcUTF83762 = 1
	codecSelferCcRAW3762  = 255
	// ----- value types used ----
	codecSelferValueTypeArray3762     = 10
	codecSelferValueTypeMap3762       = 9
	codecSelferValueTypeString3762    = 6
	codecSelferValueTypeInt3762       = 2
	codecSelferValueTypeUint3762      = 3
	codecSelferValueTypeFloat3762     = 4
	codecSelferValueTypeNil3762       = 1
	codecSelferBitsize3762            = uint8(32 << (^uint(0) >> 63))
	codecSelferDecContainerLenNil3762 = -2147483648
)

var (
	errCodecSelferOnlyMapOrArrayEncodeToStruct3762 = errors.New(`only encoded map or array can be decoded into a struct`)
)

type codecSelfer3762 struct{}

func codecSelfer3762False() bool { return false }
func codecSelfer3762True() bool  { return true }

func init() {
	if codec1978.GenVersion != 25 {
		_, file, _, _ := runtime.Caller(0)
		ver := strconv.FormatInt(int64(codec1978.GenVersion), 10)
		panic(errors.New("codecgen version mismatch: current: 25, need " + ver + ". Re-generate file: " + file))
	}
	if false { // reference the types, but skip this branch at build/run time
		var _ pkg1_v3.Message
	}
}

func (Event) codecSelferViaCodecgen() {}
func (x *Event) CodecEncodeSelf(e *codec1978.Encoder) {
	var h codecSelfer3762
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if z.EncBasicHandle().CheckCircularRef {
		z.EncEncode(x)
		return
	}
	if x == nil {
		r.EncodeNil()
	} else {
		yy2arr2 := z.EncBasicHandle().StructToArray
		_ = yy2arr2
		const yyr2 bool = false // struct tag has 'toArray'
		var yyn9 bool = x.Message.Status == nil
		var yyn10 bool = x.Message.RequestDeliveryResponse == nil
		var yyn14 bool = x.Message.IncludeSpans == nil
		var yyq2 = [19]bool{ // should field at this index be written?
			true,                             // msg_type
			x.Source != "",                   // source
			x.Destination != "",              // dest
			x.TransactionUUID != "",          // transaction_uuid
			x.ContentType != "",              // content_type
			x.Accept != "",                   // accept
			x.Status != nil,                  // status
			x.RequestDeliveryResponse != nil, // rdr
			len(x.Headers) != 0,              // headers
			len(x.Metadata) != 0,             // metadata
			len(x.Spans) != 0,                // spans
			x.IncludeSpans != nil,            // include_spans
			x.Path != "",                     // path
			len(x.Payload) != 0,              // payload
			x.ServiceName != "",              // service_name
			x.URL != "",                      // url
			len(x.PartnerIDs) != 0,           // partner_ids
			x.SessionID != "",                // session_id
			x.BirthDate != 0,                 // birth_date
		}
		_ = yyq2
		if yyr2 || yy2arr2 {
			z.EncWriteArrayStart(19)
			z.EncWriteArrayElem()
			if yyxt22 := z.Extension(x.Message.Type); yyxt22 != nil {
				z.EncExtension(x.Message.Type, yyxt22)
			} else {
				r.EncodeInt(int64(x.Message.Type))
			}
			z.EncWriteArrayElem()
			if yyq2[1] {
				r.EncodeString(string(x.Message.Source))
			} else {
				r.EncodeString("")
			}
			z.EncWriteArrayElem()
			if yyq2[2] {
				r.EncodeString(string(x.Message.Destination))
			} else {
				r.EncodeString("")
			}
			z.EncWriteArrayElem()
			if yyq2[3] {
				r.EncodeString(string(x.Message.TransactionUUID))
			} else {
				r.EncodeString("")
			}
			z.EncWriteArrayElem()
			if yyq2[4] {
				r.EncodeString(string(x.Message.ContentType))
			} else {
				r.EncodeString("")
			}
			z.EncWriteArrayElem()
			if yyq2[5] {
				r.EncodeString(string(x.Message.Accept))
			} else {
				r.EncodeString("")
			}
			if yyn9 {
				z.EncWriteArrayElem()
				r.EncodeNil()
			} else {
				z.EncWriteArrayElem()
				if yyq2[6] {
					yy28 := *x.Message.Status
					r.EncodeInt(int64(yy28))
				} else {
					r.EncodeNil()
				}
			}
			if yyn10 {
				z.EncWriteArrayElem()
				r.EncodeNil()
			} else {
				z.EncWriteArrayElem()
				if yyq2[7] {
					yy30 := *x.Message.RequestDeliveryResponse
					r.EncodeInt(int64(yy30))
				} else {
					r.EncodeNil()
				}
			}
			z.EncWriteArrayElem()
			if yyq2[8] {
				if x.Message.Headers == nil {
					r.EncodeNil()
				} else {
					z.F.EncSliceStringV(x.Message.Headers, e)
				} // end block: if x.Message.Headers slice == nil
			} else {
				r.EncodeNil()
			}
			z.EncWriteArrayElem()
			if yyq2[9] {
				if x.Message.Metadata == nil {
					r.EncodeNil()
				} else {
					z.F.EncMapStringStringV(x.Message.Metadata, e)
				} // end block: if x.Message.Metadata map == nil
			} else {
				r.EncodeNil()
			}
			z.EncWriteArrayElem()
			if yyq2[10] {
				if x.Message.Spans == nil {
					r.EncodeNil()
				} else {
					h.encSliceSlicestring(([][]string)(x.Message.Spans), e)
				} // end block: if x.Message.Spans slice == nil
			} else {
				r.EncodeNil()
			}
			if yyn14 {
				z.EncWriteArrayElem()
				r.EncodeNil()
			} else {
				z.EncWriteArrayElem()
				if yyq2[11] {
					yy35 := *x.Message.IncludeSpans
					r.EncodeBool(bool(yy35))
				} else {
					r.EncodeNil()
				}
			}
			z.EncWriteArrayElem()
			if yyq2[12] {
				r.EncodeString(string(x.Message.Path))
			} else {
				r.EncodeString("")
			}
			z.EncWriteArrayElem()
			if yyq2[13] {
				if x.Message.Payload == nil {
					r.EncodeNil()
				} else {
					r.EncodeStringBytesRaw([]byte(x.Message.Payload))
				} // end block: if x.Message.Payload slice == nil
			} else {
				r.EncodeNil()
			}
			z.EncWriteArrayElem()
			if yyq2[14] {
				r.EncodeString(string(x.Message.ServiceName))
			} else {
				r.EncodeString("")
			}
			z.EncWriteArrayElem()
			if yyq2[15] {
				r.EncodeString(string(x.Message.URL))
			} else {
				r.EncodeString("")
			}
			z.EncWriteArrayElem()
			if yyq2[16] {
				if x.Message.PartnerIDs == nil {
					r.EncodeNil()
				} else {
					z.F.EncSliceStringV(x.Message.PartnerIDs, e)
				} // end block: if x.Message.PartnerIDs slice == nil
			} else {
				r.EncodeNil()
			}
			z.EncWriteArrayElem()
			if yyq2[17] {
				r.EncodeString(string(x.Message.SessionID))
			} else {
				r.EncodeString("")
			}
			z.EncWriteArrayElem()
			if yyq2[18] {
				r.EncodeInt(int64(x.BirthDate))
			} else {
				r.EncodeInt(0)
			}
			z.EncWriteArrayEnd()
		} else {
			var yynn2 int
			for _, b := range yyq2 {
				if b {
					yynn2++
				}
			}
			z.EncWriteMapStart(yynn2)
			yynn2 = 0
			z.EncWriteMapElemKey()
			r.EncodeString(`msg_type`)
			z.EncWriteMapElemValue()
			if yyxt44 := z.Extension(x.Message.Type); yyxt44 != nil {
				z.EncExtension(x.Message.Type, yyxt44)
			} else {
				r.EncodeInt(int64(x.Message.Type))
			}
			if yyq2[1] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"source\"")
				} else {
					r.EncodeString(`source`)
				}
				z.EncWriteMapElemValue()
				r.EncodeString(string(x.Message.Source))
			}
			if yyq2[2] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"dest\"")
				} else {
					r.EncodeString(`dest`)
				}
				z.EncWriteMapElemValue()
				r.EncodeString(string(x.Message.Destination))
			}
			if yyq2[3] {
				z.EncWriteMapElemKey()
				r.EncodeString(`transaction_uuid`)
				z.EncWriteMapElemValue()
				r.EncodeString(string(x.Message.TransactionUUID))
			}
			if yyq2[4] {
				z.EncWriteMapElemKey()
				r.EncodeString(`content_type`)
				z.EncWriteMapElemValue()
				r.EncodeString(string(x.Message.ContentType))
			}
			if yyq2[5] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"accept\"")
				} else {
					r.EncodeString(`accept`)
				}
				z.EncWriteMapElemValue()
				r.EncodeString(string(x.Message.Accept))
			}
			if yyq2[6] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"status\"")
				} else {
					r.EncodeString(`status`)
				}
				z.EncWriteMapElemValue()
				if yyn9 {
					r.EncodeNil()
				} else {
					yy50 := *x.Message.Status
					r.EncodeInt(int64(yy50))
				}
			}
			if yyq2[7] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"rdr\"")
				} else {
					r.EncodeString(`rdr`)
				}
				z.EncWriteMapElemValue()
				if yyn10 {
					r.EncodeNil()
				} else {
					yy52 := *x.Message.RequestDeliveryResponse
					r.EncodeInt(int64(yy52))
				}
			}
			if yyq2[8] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"headers\"")
				} else {
					r.EncodeString(`headers`)
				}
				z.EncWriteMapElemValue()
				if x.Message.Headers == nil {
					r.EncodeNil()
				} else {
					z.F.EncSliceStringV(x.Message.Headers, e)
				} // end block: if x.Message.Headers slice == nil
			}
			if yyq2[9] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"metadata\"")
				} else {
					r.EncodeString(`metadata`)
				}
				z.EncWriteMapElemValue()
				if x.Message.Metadata == nil {
					r.EncodeNil()
				} else {
					z.F.EncMapStringStringV(x.Message.Metadata, e)
				} // end block: if x.Message.Metadata map == nil
			}
			if yyq2[10] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"spans\"")
				} else {
					r.EncodeString(`spans`)
				}
				z.EncWriteMapElemValue()
				if x.Message.Spans == nil {
					r.EncodeNil()
				} else {
					h.encSliceSlicestring(([][]string)(x.Message.Spans), e)
				} // end block: if x.Message.Spans slice == nil
			}
			if yyq2[11] {
				z.EncWriteMapElemKey()
				r.EncodeString(`include_spans`)
				z.EncWriteMapElemValue()
				if yyn14 {
					r.EncodeNil()
				} else {
					yy57 := *x.Message.IncludeSpans
					r.EncodeBool(bool(yy57))
				}
			}
			if yyq2[12] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"path\"")
				} else {
					r.EncodeString(`path`)
				}
				z.EncWriteMapElemValue()
				r.EncodeString(string(x.Message.Path))
			}
			if yyq2[13] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"payload\"")
				} else {
					r.EncodeString(`payload`)
				}
				z.EncWriteMapElemValue()
				if x.Message.Payload == nil {
					r.EncodeNil()
				} else {
					r.EncodeStringBytesRaw([]byte(x.Message.Payload))
				} // end block: if x.Message.Payload slice == nil
			}
			if yyq2[14] {
				z.EncWriteMapElemKey()
				r.EncodeString(`service_name`)
				z.EncWriteMapElemValue()
				r.EncodeString(string(x.Message.ServiceName))
			}
			if yyq2[15] {
				z.EncWriteMapElemKey()
				if z.IsJSONHandle() {
					z.WriteStr("\"url\"")
				} else {
					r.EncodeString(`url`)
				}
				z.EncWriteMapElemValue()
				r.EncodeString(string(x.Message.URL))
			}
			if yyq2[16] {
				z.EncWriteMapElemKey()
				r.EncodeString(`partner_ids`)
				z.EncWriteMapElemValue()
				if x.Message.PartnerIDs == nil {
					r.EncodeNil()
				} else {
					z.F.EncSliceStringV(x.Message.PartnerIDs, e)
				} // end block: if x.Message.PartnerIDs slice == nil
			}
			if yyq2[17] {
				z.EncWriteMapElemKey()
				r.EncodeString(`session_id`)
				z.EncWriteMapElemValue()
				r.EncodeString(string(x.Message.SessionID))
			}
			if yyq2[18] {
				z.EncWriteMapElemKey()
				r.EncodeString(`birth_date`)
				z.EncWriteMapElemValue()
				r.EncodeInt(int64(x.BirthDate))
			}
			z.EncWriteMapEnd()
		}
	}
}

func (x *Event) CodecDecodeSelf(d *codec1978.Decoder) {
	var h codecSelfer3762
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	yyct2 := r.ContainerType()
	if yyct2 == codecSelferValueTypeNil3762 {
		*(x) = Event{}
	} else if yyct2 == codecSelferValueTypeMap3762 {
		yyl2 := z.DecReadMapStart()
		if yyl2 == 0 {
		} else {
			x.codecDecodeSelfFromMap(yyl2, d)
		}
		z.DecReadMapEnd()
	} else if yyct2 == codecSelferValueTypeArray3762 {
		yyl2 := z.DecReadArrayStart()
		if yyl2 != 0 {
			x.codecDecodeSelfFromArray(yyl2, d)
		}
		z.DecReadArrayEnd()
	} else {
		panic(errCodecSelferOnlyMapOrArrayEncodeToStruct3762)
	}
}

func (x *Event) codecDecodeSelfFromMap(l int, d *codec1978.Decoder) {
	var h codecSelfer3762
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyhl3 bool = l >= 0
	for yyj3 := 0; ; yyj3++ {
		if yyhl3 {
			if yyj3 >= l {
				break
			}
		} else {
			if z.DecCheckBreak() {
				break
			}
		}
		z.DecReadMapElemKey()
		yys3 := r.DecodeStringAsBytes()
		z.DecReadMapElemValue()
		switch string(yys3) {
		case "msg_type":
			if yyxt5 := z.Extension(x.Message.Type); yyxt5 != nil {
				z.DecExtension(&x.Message.Type, yyxt5)
			} else {
				x.Message.Type = (pkg1_v3.MessageType)(r.DecodeInt64())
			}
		case "source":
			x.Message.Source = (string)(z.DecStringZC(r.DecodeStringAsBytes()))
		case "dest":
			x.Message.Destination = (string)(z.DecStringZC(r.DecodeStringAsBytes()))
		case "transaction_uuid":
			x.Message.TransactionUUID = (string)(z.DecStringZC(r.DecodeStringAsBytes()))
		case "content_type":
			x.Message.ContentType = (string)(z.DecStringZC(r.DecodeStringAsBytes()))
		case "accept":
			x.Message.Accept = (string)(z.DecStringZC(r.DecodeStringAsBytes()))
		case "status":
			if r.TryNil() {
				if x.Message.Status != nil { // remove the if-true
					x.Message.Status = nil
				}
			} else {
				if x.Message.Status == nil {
					x.Message.Status = new(int64)
				}
				*x.Message.Status = (int64)(r.DecodeInt64())
			}
		case "rdr":
			if r.TryNil() {
				if x.Message.RequestDeliveryResponse != nil { // remove the if-true
					x.Message.RequestDeliveryResponse = nil
				}
			} else {
				if x.Message.RequestDeliveryResponse == nil {
					x.Message.RequestDeliveryResponse = new(int64)
				}
				*x.Message.RequestDeliveryResponse = (int64)(r.DecodeInt64())
			}
		case "headers":
			z.F.DecSliceStringX(&x.Message.Headers, d)
		case "metadata":
			z.F.DecMapStringStringX(&x.Message.Metadata, d)
		case "spans":
			h.decSliceSlicestring((*[][]string)(&x.Message.Spans), d)
		case "include_spans":
			if r.TryNil() {
				if x.Message.IncludeSpans != nil { // remove the if-true
					x.Message.IncludeSpans = nil
				}
			} else {
				if x.Message.IncludeSpans == nil {
					x.Message.IncludeSpans = new(bool)
				}
				*x.Message.IncludeSpans = (bool)(r.DecodeBool())
			}
		case "path":
			x.Message.Path = (string)(z.DecStringZC(r.DecodeStringAsBytes()))
		case "payload":
			x.Message.Payload = z.DecodeBytesInto(([]byte)(x.Message.Payload))
		case "service_name":
			x.Message.ServiceName = (string)(z.DecStringZC(r.DecodeStringAsBytes()))
		case "url":
			x.Message.URL = (string)(z.DecStringZC(r.DecodeStringAsBytes()))
		case "partner_ids":
			z.F.DecSliceStringX(&x.Message.PartnerIDs, d)
		case "session_id":
			x.Message.SessionID = (string)(z.DecStringZC(r.DecodeStringAsBytes()))
		case "birth_date":
			x.BirthDate = (int64)(r.DecodeInt64())
		default:
			z.DecStructFieldNotFound(-1, string(yys3))
		} // end switch yys3
	} // end for yyj3
}

func (x *Event) codecDecodeSelfFromArray(l int, d *codec1978.Decoder) {
	var h codecSelfer3762
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r
	var yyj32 int
	var yyb32 bool
	var yyhl32 bool = l >= 0
	yyj32++
	if yyhl32 {
		yyb32 = yyj32 > l
	} else {
		yyb32 = z.DecCheckBreak()
	}
	if yyb32 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	if yyxt34 := z.Extension(x.Message.Type); yyxt34 != nil {
		z.DecExtension(&x.Message.Type, yyxt34)
	} else {
		x.Message.Type = (pkg1_v3.MessageType)(r.DecodeInt64())
	}
	yyj32++
	if yyhl32 {
		yyb32 = yyj32 > l
	} else {
		yyb32 = z.DecCheckBreak()
	}
	if yyb32 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	x.Message.Source = (string)(z.DecStringZC(r.DecodeStringAsBytes()))
	yyj32++
	if yyhl32 {
		yyb32 = yyj32 > l
	} else {
		yyb32 = z.DecCheckBreak()
	}
	if yyb32 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	x.Message.Destination = (string)(z.DecStringZC(r.DecodeStringAsBytes()))
	yyj32++
	if yyhl32 {
		yyb32 = yyj32 > l
	} else {
		yyb32 = z.DecCheckBreak()
	}
	if yyb32 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	x.Message.TransactionUUID = (string)(z.DecStringZC(r.DecodeStringAsBytes()))
	yyj32++
	if yyhl32 {
		yyb32 = yyj32 > l
	} else {
		yyb32 = z.DecCheckBreak()
	}
	if yyb32 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	x.Message.ContentType = (string)(z.DecStringZC(r.DecodeStringAsBytes()))
	yyj32++
	if yyhl32 {
		yyb32 = yyj32 > l
	} else {
		yyb32 = z.DecCheckBreak()
	}
	if yyb32 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	x.Message.Accept = (string)(z.DecStringZC(r.DecodeStringAsBytes()))
	yyj32++
	if yyhl32 {
		yyb32 = yyj32 > l
	} else {
		yyb32 = z.DecCheckBreak()
	}
	if yyb32 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	if r.TryNil() {
		if x.Message.Status != nil { // remove the if-true
			x.Message.Status = nil
		}
	} else {
		if x.Message.Status == nil {
			x.Message.Status = new(int64)
		}
		*x.Message.Status = (int64)(r.DecodeInt64())
	}
	yyj32++
	if yyhl32 {
		yyb32 = yyj32 > l
	} else {
		yyb32 = z.DecCheckBreak()
	}
	if yyb32 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	if r.TryNil() {
		if x.Message.RequestDeliveryResponse != nil { // remove the if-true
			x.Message.RequestDeliveryResponse = nil
		}
	} else {
		if x.Message.RequestDeliveryResponse == nil {
			x.Message.RequestDeliveryResponse = new(int64)
		}
		*x.Message.RequestDeliveryResponse = (int64)(r.DecodeInt64())
	}
	yyj32++
	if yyhl32 {
		yyb32 = yyj32 > l
	} else {
		yyb32 = z.DecCheckBreak()
	}
	if yyb32 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	z.F.DecSliceStringX(&x.Message.Headers, d)
	yyj32++
	if yyhl32 {
		yyb32 = yyj32 > l
	} else {
		yyb32 = z.DecCheckBreak()
	}
	if yyb32 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	z.F.DecMapStringStringX(&x.Message.Metadata, d)
	yyj32++
	if yyhl32 {
		yyb32 = yyj32 > l
	} else {
		yyb32 = z.DecCheckBreak()
	}
	if yyb32 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	h.decSliceSlicestring((*[][]string)(&x.Message.Spans), d)
	yyj32++
	if yyhl32 {
		yyb32 = yyj32 > l
	} else {
		yyb32 = z.DecCheckBreak()
	}
	if yyb32 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	if r.TryNil() {
		if x.Message.IncludeSpans != nil { // remove the if-true
			x.Message.IncludeSpans = nil
		}
	} else {
		if x.Message.IncludeSpans == nil {
			x.Message.IncludeSpans = new(bool)
		}
		*x.Message.IncludeSpans = (bool)(r.DecodeBool())
	}
	yyj32++
	if yyhl32 {
		yyb32 = yyj32 > l
	} else {
		yyb32 = z.DecCheckBreak()
	}
	if yyb32 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	x.Message.Path = (string)(z.DecStringZC(r.DecodeStringAsBytes()))
	yyj32++
	if yyhl32 {
		yyb32 = yyj32 > l
	} else {
		yyb32 = z.DecCheckBreak()
	}
	if yyb32 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	x.Message.Payload = z.DecodeBytesInto(([]byte)(x.Message.Payload))
	yyj32++
	if yyhl32 {
		yyb32 = yyj32 > l
	} else {
		yyb32 = z.DecCheckBreak()
	}
	if yyb32 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	x.Message.ServiceName = (string)(z.DecStringZC(r.DecodeStringAsBytes()))
	yyj32++
	if yyhl32 {
		yyb32 = yyj32 > l
	} else {
		yyb32 = z.DecCheckBreak()
	}
	if yyb32 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	x.Message.URL = (string)(z.DecStringZC(r.DecodeStringAsBytes()))
	yyj32++
	if yyhl32 {
		yyb32 = yyj32 > l
	} else {
		yyb32 = z.DecCheckBreak()
	}
	if yyb32 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	z.F.DecSliceStringX(&x.Message.PartnerIDs, d)
	yyj32++
	if yyhl32 {
		yyb32 = yyj32 > l
	} else {
		yyb32 = z.DecCheckBreak()
	}
	if yyb32 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	x.Message.SessionID = (string)(z.DecStringZC(r.DecodeStringAsBytes()))
	yyj32++
	if yyhl32 {
		yyb32 = yyj32 > l
	} else {
		yyb32 = z.DecCheckBreak()
	}
	if yyb32 {
		z.DecReadArrayEnd()
		return
	}
	z.DecReadArrayElem()
	x.BirthDate = (int64)(r.DecodeInt64())
	for {
		yyj32++
		if yyhl32 {
			yyb32 = yyj32 > l
		} else {
			yyb32 = z.DecCheckBreak()
		}
		if yyb32 {
			break
		}
		z.DecReadArrayElem()
		z.DecStructFieldNotFound(yyj32-1, "")
	}
}

func (x *Event) IsCodecEmpty() bool {
	return !(false || x.Message.Type != 0 || x.Message.Source != "" || x.Message.Destination != "" || x.Message.TransactionUUID != "" || x.Message.ContentType != "" || x.Message.Accept != "" || x.Message.Status != nil || x.Message.RequestDeliveryResponse != nil || len(x.Message.Headers) != 0 || len(x.Message.Metadata) != 0 || len(x.Message.Spans) != 0 || x.Message.IncludeSpans != nil || x.Message.Path != "" || len(x.Message.Payload) != 0 || x.Message.ServiceName != "" || x.Message.URL != "" || len(x.Message.PartnerIDs) != 0 || x.Message.SessionID != "" || x.BirthDate != 0 || false)
}

func (x codecSelfer3762) encSliceSlicestring(v [][]string, e *codec1978.Encoder) {
	var h codecSelfer3762
	z, r := codec1978.GenHelper().Encoder(e)
	_, _, _ = h, z, r
	if v == nil {
		r.EncodeNil()
		return
	}
	z.EncWriteArrayStart(len(v))
	for yyv1 := range v {
		z.EncWriteArrayElem()
		if v[yyv1] == nil {
			r.EncodeNil()
		} else {
			z.F.EncSliceStringV(v[yyv1], e)
		} // end block: if v[yyv1] slice == nil
	}
	z.EncWriteArrayEnd()
}

func (x codecSelfer3762) decSliceSlicestring(v *[][]string, d *codec1978.Decoder) {
	var h codecSelfer3762
	z, r := codec1978.GenHelper().Decoder(d)
	_, _, _ = h, z, r

	yyv1 := *v
	yyh1, yyl1 := z.DecSliceHelperStart()
	var yyc1 bool
	_ = yyc1
	if yyh1.IsNil {
		if yyv1 != nil {
			yyv1 = nil
			yyc1 = true
		}
	} else if yyl1 == 0 {
		if yyv1 == nil {
			yyv1 = [][]string{}
			yyc1 = true
		} else if len(yyv1) != 0 {
			yyv1 = yyv1[:0]
			yyc1 = true
		}
	} else {
		yyhl1 := yyl1 > 0
		var yyrl1 int
		_ = yyrl1
		if yyhl1 {
			if yyl1 > cap(yyv1) {
				yyrl1 = z.DecInferLen(yyl1, z.DecBasicHandle().MaxInitLen, 24)
				if yyrl1 <= cap(yyv1) {
					yyv1 = yyv1[:yyrl1]
				} else {
					yyv1 = make([][]string, yyrl1)
				}
				yyc1 = true
			} else if yyl1 != len(yyv1) {
				yyv1 = yyv1[:yyl1]
				yyc1 = true
			}
		}
		var yyj1 int
		for yyj1 = 0; (yyhl1 && yyj1 < yyl1) || !(yyhl1 || z.DecCheckBreak()); yyj1++ { // bounds-check-elimination
			if yyj1 == 0 && yyv1 == nil {
				if yyhl1 {
					yyrl1 = z.DecInferLen(yyl1, z.DecBasicHandle().MaxInitLen, 24)
				} else {
					yyrl1 = 8
				}
				yyv1 = make([][]string, yyrl1)
				yyc1 = true
			}
			yyh1.ElemContainerState(yyj1)
			var yydb1 bool
			if yyj1 >= len(yyv1) {
				yyv1 = append(yyv1, nil)
				yyc1 = true
			}
			if yydb1 {
				z.DecSwallow()
			} else {
				z.F.DecSliceStringX(&yyv1[yyj1], d)
			}
		}
		if yyj1 < len(yyv1) {
			yyv1 = yyv1[:yyj1]
			yyc1 = true
		} else if yyj1 == 0 && yyv1 == nil {
			yyv1 = [][]string{}
			yyc1 = true
		}
	}
	yyh1.End()
	if yyc1 {
		*v = yyv1
	}
}
